name: API-Football ETL

on:
  workflow_dispatch:
    inputs:
      season:
        description: "Stagione Serie A"
        required: true
        default: "2024"
        type: string

jobs:
  ingestion:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests supabase

      - name: Run ingestion
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          SEASON: ${{ inputs.season }}
        run: |
          python etl_ingestion.py
